# Generated by Django 5.2.17 on 2026-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
